### ISSUE TITLE
似乎是评论区的Bug？

### ISSUE THREAD

**Issue by desiwen** [Kilerd/Cat#2]
评论提交之后评论框会自动填写上一个评论者的信息。

**Comment by Kilerd** [comment]
应该不会啊。
麻烦可以提供BUG出现的网址，或者复现一下BUG出现的过程？

**Comment by desiwen** [comment]
https://desiiii.com
提交评论之后会显示最近一个评论者的信息。

**Comment by Kilerd** [comment]
我打开你的任意一篇文章都没有评论者的消息。

评论过之后，typecho 会把提交的用户信息保存进 cookies，方便下一次评论。

至于能看到其他用户的信息，这个问题我没有遇到过，也没有其他用户反馈过这个问题。

**Comment by desiwen** [comment]
看了一下，可能是我缓存设置的问题。谢谢！
