### ISSUE TITLE
移植到了Hugo

### ISSUE THREAD

**Issue by hoofs** [Kilerd/Cat#3]
很喜欢这种小清新风格的主题，非常感谢开发者的工作。

> The reason I call this theme as Cat is hoping that it can expand to all blog engines with its flexibility.

因此把它移植到了hugo上。
虽然做的很粗糙，但还是希望作者能够在Support上加上这个[Cat](https://github.com/hoofs/Cat)链接，以便来者。
Thanks a lot.

**Comment by Kilerd** [comment]
okay, I made it.
Thanks for all the works you did for Cat Theme.
